version: "3.3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8098:4000"
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: $API_URL
    expose:
      - "80"
