# this version adds Redis (tile cache) and replicas (4x api, 4x downloader)
version: "3.3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis-data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  db:
    image: "postgis/postgis:13-3.1-alpine"
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    environment:
      - "PGPORT=${DB_PORT:-5432}"
      - "POSTGRES_DB=$DB_NAME"
      - "POSTGRES_PASSWORD=$DB_PASSWORD"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
  web-api:
    build: ./web-api
    env_file:
      - .env
    expose:
      - "4000"
    depends_on:
      - db
      - redis
    deploy:
      replicas: 4
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-api
    ports:
      - "8080:4000"
  scheduler:
    build:
      # Scheduler needs context ., see the dockerfile
      context: .
      dockerfile: ./scheduler/Dockerfile
    depends_on:
      - db
    deploy:
      replicas: 4
    env_file:
      - .env
    volumes:
      - $DOWNLOADS_FOLDER:/usr/src/app/downloads
    restart: always
  # This would get used if/when we stop hosting Gitpages
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: $API_URL
    expose:
      - "80"
    depends_on:
      - web-api
volumes:
  postgres-data:
  redis-data:
