version: "3.3"
services:
  db:
    image: "$DOCKER_POSTGIS_REPO/postgis:13-3.1-alpine"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=$DB_NAME"
      - "POSTGRES_PASSWORD=$DB_PASSWORD"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  web-api:
    build: ./web-api
    env_file:
      - .env
    expose:
      - "4000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-api
    ports:
      - "5050:4000"
  scheduler:
    build:
      context: .
      dockerfile: ./scheduler/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - $DOWNLOADS_FOLDER:/usr/src/app/downloads
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: $API_URL
    expose:
      - "80"
    depends_on:
      - web-api
volumes:
  postgres-data:
