# list of erddap URLs. Should end in /erddap
erddap_urls:
  - https://catalogue.hakai.org/erddap

# set to true to test with caching. Not available in production docker compose file
# defaults to false
cache:

# defaults to 'harvest'
folder: 

# use to test select datasets, eg: dataset_one,dataset_two
dataset_ids:  

# defaults to false
log_time:  