name: Build and Test

on:
  push:
    paths:
      - "downloader/**"

jobs:
  build-and-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install downloader and harvester
        run: |
          pip install -q ./harvester
          pip install -q ./downloader

      - name: Run downloader test files
        working-directory: ./downloader
        run: sh test_downloader.sh
